language: java

jdk:
  - openjdk7
  - openjdk8
  - oraclejdk8
  - openjdk9
  - openjdk10
  - openjdk11
  - openjdk12
  - oraclejdk9

env:
  global:
    - SURGE_LOGIN=jrossi@scmgroup.it
    - secure: VX+KGZlhN4j4lE9zU6c7PUjAuWJHMgPqC0eG3ebOJ0Xq/q7LW4RDqyeJxu4g7Erlo3OR9r3O+2uFvvdzgI6Bh1I5ezXjTMMrYkDep6bK1+LcIOXfZS1RSY7vtxYXjyh0ZT3cHeyiIljN0jRK2s+wV7cWmiI9EY7Y1YiMR2IoZJGSsiPcj88rtSTxAnvauqzSi9425600BecyLCX8aB5lkRdzYknegHP3VnAENLKsNJPzoZwqaCtFwEkIMkNnL/qO3CIDfOeubiqfYdLeDSpj3iQx1OhcJzavm03x5IyIWjrzexCwu7DaNwo/vHiwve8RG4qdF4foUHUV5cUiILlrQt8cAWrRHylUPAKK0rAS8FO6uI1s1BWjAlRuH/BntA817LAsGme/I4NK85fX6rADXtLYruvcLxuM2KvLCQ+bNvu2HHVZc2ugxNk7MQDaSXhey3FlxWQR8Ga/v99BegqRb6MpNUfGz0aOdGEDUrJ78VGuOEI7Xtv0sDhryHMPOLYwG+VpeLmzLY0/4+CKBdDqezIDhK3SPkvN55ufc3B7QkH3skjTEnOIgMVcWiH91TX4/d7wEnUP8tQwsfBeARZQJV+IUO9WbiMSnBM1ouSHHPO90Q+ze0QhbvEmRjYDTQHKPi7tdC5TBx1YHRcZuEG3JMh4ncnDY342AzMqvb7PS5I=

# Disable Travis install phase
install: true

# Execute our custom build
script:
  - ./gradlew clean buildDashboard

deploy:
  provider: surge
  project: build/reports/
  domain: myGradleWrapper.surge.sh
  skip_cleanup: true
  on:
    all_branches: true
